local character_layer = require("modules.character.character_layer")

go.property("default", resource.tile_source("/assets/characters/default_tool.tilesource"))
go.property("pickaxe", resource.tile_source("/assets/characters/pickaxe/pickaxe.tilesource"))
go.property("sword", resource.tile_source("/assets/characters/sword/sword.tilesource"))
go.property("axe", resource.tile_source("/assets/characters/axe/axe.tilesource"))
go.property("rod", resource.tile_source("/assets/characters/fishing/rod.tilesource"))
go.property("hoe", resource.tile_source("/assets/characters/hoe/hoe.tilesource"))
go.property("watering", resource.tile_source("/assets/characters/watering/watering.tilesource"))

local layer = character_layer.create({
	sprite_url = "#tool",
})

function init(self)
	layer.init(self)
end

function on_message(self, message_id, message, sender)
	layer.on_message(self, message_id, message)
end
