local character_info = require('modules.character.character_information')
local character_looks = require('modules.character.character_looks')
local character_animation_module = require('modules.character.animation.character_animation')
local character_animation = character_animation_module.new()

local default_pos

go.property("default", resource.tile_source("/assets/characters/walk/clothes/body/basic.tilesource"))
go.property("floral", resource.tile_source("/assets/characters/walk/clothes/body/floral.tilesource"))
go.property("overall", resource.tile_source("/assets/characters/walk/clothes/body/overall.tilesource"))
go.property("sailor", resource.tile_source("/assets/characters/walk/clothes/body/sailor.tilesource"))
go.property("sailor_bow", resource.tile_source("/assets/characters/walk/clothes/body/sailor_bow.tilesource"))
go.property("sporty", resource.tile_source("/assets/characters/walk/clothes/body/sporty.tilesource"))
go.property("suit", resource.tile_source("/assets/characters/walk/clothes/body/suit.tilesource"))


go.property("default_carry", resource.tile_source("/assets/characters/carrying/clothes/body/basic_carry.tilesource"))
go.property("floral_carry", resource.tile_source("/assets/characters/carrying/clothes/body/floral_carry.tilesource"))
go.property("overall_carry", resource.tile_source("/assets/characters/carrying/clothes/body/overall_carry.tilesource"))
go.property("sailor_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sailor_carry.tilesource"))
go.property("sailor_bow_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sailor_bow_carry.tilesource"))
go.property("sporty_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sporty_carry.tilesource"))
go.property("suit_carry", resource.tile_source("/assets/characters/carrying/clothes/body/suit_carry.tilesource"))

go.property("default_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/basic_pickaxe.tilesource"))
go.property("floral_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/floral_pickaxe.tilesource"))
go.property("overall_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/overall_pickaxe.tilesource"))
go.property("sailor_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sailor_pickaxe.tilesource"))
go.property("sailor_bow_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sailor_bow_pickaxe.tilesource"))
go.property("sporty_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sporty_pickaxe.tilesource"))
go.property("suit_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/suit_pickaxe.tilesource"))

go.property("default_sword", resource.tile_source("/assets/characters/sword/clothes/body/basic_sword.tilesource"))
go.property("floral_sword", resource.tile_source("/assets/characters/sword/clothes/body/floral_sword.tilesource"))
go.property("overall_sword", resource.tile_source("/assets/characters/sword/clothes/body/overall_sword.tilesource"))
go.property("sailor_sword", resource.tile_source("/assets/characters/sword/clothes/body/sailor_sword.tilesource"))
go.property("sailor_bow_sword", resource.tile_source("/assets/characters/sword/clothes/body/sailor_bow_sword.tilesource"))
go.property("sporty_sword", resource.tile_source("/assets/characters/sword/clothes/body/sporty_sword.tilesource"))
go.property("suit_sword", resource.tile_source("/assets/characters/sword/clothes/body/suit_sword.tilesource"))

go.property("default_axe", resource.tile_source("/assets/characters/axe/clothes/body/basic_axe.tilesource"))
go.property("floral_axe", resource.tile_source("/assets/characters/axe/clothes/body/floral_axe.tilesource"))
go.property("overall_axe", resource.tile_source("/assets/characters/axe/clothes/body/overall_axe.tilesource"))
go.property("sailor_axe", resource.tile_source("/assets/characters/axe/clothes/body/sailor_axe.tilesource"))
go.property("sailor_bow_axe", resource.tile_source("/assets/characters/axe/clothes/body/sailor_bow_axe.tilesource"))
go.property("sporty_axe", resource.tile_source("/assets/characters/axe/clothes/body/sporty_axe.tilesource"))
go.property("suit_axe", resource.tile_source("/assets/characters/axe/clothes/body/suit_axe.tilesource"))

go.property("default_rod", resource.tile_source("/assets/characters/fishing/clothes/body/basic_fish.tilesource"))
go.property("floral_rod", resource.tile_source("/assets/characters/fishing/clothes/body/floral_fish.tilesource"))
go.property("overall_rod", resource.tile_source("/assets/characters/fishing/clothes/body/overall_fish.tilesource"))
go.property("sailor_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sailor_fish.tilesource"))
go.property("sailor_bow_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sailor_bow_fish.tilesource"))
go.property("sporty_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sporty_fish.tilesource"))
go.property("suit_rod", resource.tile_source("/assets/characters/fishing/clothes/body/suit_fish.tilesource"))

go.property("default_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/basic_hoe.tilesource"))
go.property("floral_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/floral_hoe.tilesource"))
go.property("overall_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/overall_hoe.tilesource"))
go.property("sailor_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sailor_hoe.tilesource"))
go.property("sailor_bow_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sailor_bow_hoe.tilesource"))
go.property("sporty_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sporty_hoe.tilesource"))
go.property("suit_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/suit_hoe.tilesource"))

go.property("default_watering", resource.tile_source("/assets/characters/watering/clothes/body/basic_watering.tilesource"))
go.property("floral_watering", resource.tile_source("/assets/characters/watering/clothes/body/floral_watering.tilesource"))
go.property("overall_watering", resource.tile_source("/assets/characters/watering/clothes/body/overall_watering.tilesource"))
go.property("sailor_watering", resource.tile_source("/assets/characters/watering/clothes/body/sailor_watering.tilesource"))
go.property("sailor_bow_watering", resource.tile_source("/assets/characters/watering/clothes/body/sailor_bow_watering.tilesource"))
go.property("sporty_watering", resource.tile_source("/assets/characters/watering/clothes/body/sporty_watering.tilesource"))
go.property("suit_watering", resource.tile_source("/assets/characters/watering/clothes/body/suit_watering.tilesource"))

local function get_shirt_style(self)
    if character_info.is_carrying then
        local styles = {
            self.floral_carry,
            self.overall_carry,
            self.sailor_carry,
            self.sailor_bow_carry,
            self.sporty_carry,
            self.suit_carry
        }
        return styles[character_looks.style[2]] or self.default_carry
    else
        local styles = {
            self.floral,
            self.overall,
            self.sailor,
            self.sailor_bow,
            self.sporty,
            self.suit
        }
        return styles[character_looks.style[2]] or self.default
    end
end

local function get_tool_shirt_style(self, action)
    if action == 'Pickaxe' then
        local styles = {
            self.floral_pickaxe,
            self.overall_pickaxe,
            self.sailor_pickaxe,
            self.sailor_bow_pickaxe,
            self.sporty_pickaxe,
            self.suit_pickaxe
        }
        return styles[character_looks.style[2]] or self.default_pickaxe
    elseif action == 'Axe' then
        local styles = {
            self.floral_axe,
            self.overall_axe,
            self.sailor_axe,
            self.sailor_bow_axe,
            self.sporty_axe,
            self.suit_axe
        }
        return styles[character_looks.style[2]] or self.default_axe
    elseif action == 'Sword' then
        local styles = {
            self.floral_sword,
            self.overall_sword,
            self.sailor_sword,
            self.sailor_bow_sword,
            self.sporty_sword,
            self.suit_sword
        }
        return styles[character_looks.style[2]] or self.default_sword
    elseif action == 'Fishing rod' then
        local styles = {
            self.floral_rod,
            self.overall_rod,
            self.sailor_rod,
            self.sailor_bow_rod,
            self.sporty_rod,
            self.suit_rod
        }
        return styles[character_looks.style[2]] or self.default_rod
    elseif action == 'Hoe' then
        local styles = {
            self.floral_hoe,
            self.overall_hoe,
            self.sailor_hoe,
            self.sailor_bow_hoe,
            self.sporty_hoe,
            self.suit_hoe
        }
        return styles[character_looks.style[2]] or self.default_hoe
    elseif action == 'Watering can' then
        local styles = {
            self.floral_watering,
            self.overall_watering,
            self.sailor_watering,
            self.sailor_bow_watering,
            self.sporty_watering,
            self.suit_watering
        }
        return styles[character_looks.style[2]] or self.default_watering
    end
    return self.default_pickaxe
end

function init(self)
	character_animation.reset_animation("#shirt", get_shirt_style(self), true)
    default_pos = go.get_position()

    self.animations = {
		Pickaxe = vmath.vector3(0, 0, 0),
		Axe = vmath.vector3(0, 0, 0),
		Sword = vmath.vector3(0, 0, 0),
		['Fising rod'] = vmath.vector3(0, -4, 0),
		Hoe = vmath.vector3(0, -7, 0),
		['Watering can'] = vmath.vector3(0, -5, 0)
	}
end

function on_message(self, message_id, message, sender)
	if message_id == hash('reset_animation') then
		character_animation.reset_animation("#shirt", get_shirt_style(self), true)
	elseif message_id == hash("animate") then
		character_animation.play_animation("#shirt", message.direction)
	elseif message_id == hash('animate_character') then
        character_animation.start_animation("#shirt", get_tool_shirt_style(self, message.name))
        local position = self.animations[message.name]
		if message.name == 'Hoe' and character_info.direction ~= 'down' then
			position = vmath.vector3(0, -1, 0)
		end
		go.set_position(position)
	end

	character_animation.on_message(message_id, "#shirt", get_shirt_style(self), default_pos)
end