local character_layer = require("modules.character.character_layer")

go.property("default", resource.tile_source("/assets/characters/walk/character.tilesource"))
go.property("carry", resource.tile_source("/assets/characters/carrying/character_carry.tilesource"))
go.property("pickaxe", resource.tile_source("/assets/characters/pickaxe/character_pickaxe.tilesource"))
go.property("sword", resource.tile_source("/assets/characters/sword/character_sword.tilesource"))
go.property("axe", resource.tile_source("/assets/characters/axe/character_axe.tilesource"))
go.property("rod", resource.tile_source("/assets/characters/fishing/character_rod.tilesource"))
go.property("hoe", resource.tile_source("/assets/characters/hoe/character_hoe.tilesource"))
go.property("watering", resource.tile_source("/assets/characters/watering/character_watering.tilesource"))

local layer = character_layer.create({
	sprite_url = "#body",
})

function init(self)
	layer.init(self)
end

function on_message(self, message_id, message, sender)
	layer.on_message(self, message_id, message)
end
