local character_layer = require("modules.character.character_layer")

go.property("default", resource.tile_source("/assets/characters/walk/clothes/body/basic.tilesource"))
go.property("floral", resource.tile_source("/assets/characters/walk/clothes/body/floral.tilesource"))
go.property("overall", resource.tile_source("/assets/characters/walk/clothes/body/overall.tilesource"))
go.property("sailor", resource.tile_source("/assets/characters/walk/clothes/body/sailor.tilesource"))
go.property("sailor_bow", resource.tile_source("/assets/characters/walk/clothes/body/sailor_bow.tilesource"))
go.property("sporty", resource.tile_source("/assets/characters/walk/clothes/body/sporty.tilesource"))
go.property("suit", resource.tile_source("/assets/characters/walk/clothes/body/suit.tilesource"))

go.property("default_carry", resource.tile_source("/assets/characters/carrying/clothes/body/basic_carry.tilesource"))
go.property("floral_carry", resource.tile_source("/assets/characters/carrying/clothes/body/floral_carry.tilesource"))
go.property("overall_carry", resource.tile_source("/assets/characters/carrying/clothes/body/overall_carry.tilesource"))
go.property("sailor_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sailor_carry.tilesource"))
go.property("sailor_bow_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sailor_bow_carry.tilesource"))
go.property("sporty_carry", resource.tile_source("/assets/characters/carrying/clothes/body/sporty_carry.tilesource"))
go.property("suit_carry", resource.tile_source("/assets/characters/carrying/clothes/body/suit_carry.tilesource"))

go.property("default_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/basic_pickaxe.tilesource"))
go.property("floral_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/floral_pickaxe.tilesource"))
go.property("overall_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/overall_pickaxe.tilesource"))
go.property("sailor_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sailor_pickaxe.tilesource"))
go.property("sailor_bow_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sailor_bow_pickaxe.tilesource"))
go.property("sporty_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/sporty_pickaxe.tilesource"))
go.property("suit_pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/body/suit_pickaxe.tilesource"))

go.property("default_sword", resource.tile_source("/assets/characters/sword/clothes/body/basic_sword.tilesource"))
go.property("floral_sword", resource.tile_source("/assets/characters/sword/clothes/body/floral_sword.tilesource"))
go.property("overall_sword", resource.tile_source("/assets/characters/sword/clothes/body/overall_sword.tilesource"))
go.property("sailor_sword", resource.tile_source("/assets/characters/sword/clothes/body/sailor_sword.tilesource"))
go.property("sailor_bow_sword", resource.tile_source("/assets/characters/sword/clothes/body/sailor_bow_sword.tilesource"))
go.property("sporty_sword", resource.tile_source("/assets/characters/sword/clothes/body/sporty_sword.tilesource"))
go.property("suit_sword", resource.tile_source("/assets/characters/sword/clothes/body/suit_sword.tilesource"))

go.property("default_axe", resource.tile_source("/assets/characters/axe/clothes/body/basic_axe.tilesource"))
go.property("floral_axe", resource.tile_source("/assets/characters/axe/clothes/body/floral_axe.tilesource"))
go.property("overall_axe", resource.tile_source("/assets/characters/axe/clothes/body/overall_axe.tilesource"))
go.property("sailor_axe", resource.tile_source("/assets/characters/axe/clothes/body/sailor_axe.tilesource"))
go.property("sailor_bow_axe", resource.tile_source("/assets/characters/axe/clothes/body/sailor_bow_axe.tilesource"))
go.property("sporty_axe", resource.tile_source("/assets/characters/axe/clothes/body/sporty_axe.tilesource"))
go.property("suit_axe", resource.tile_source("/assets/characters/axe/clothes/body/suit_axe.tilesource"))

go.property("default_rod", resource.tile_source("/assets/characters/fishing/clothes/body/basic_fish.tilesource"))
go.property("floral_rod", resource.tile_source("/assets/characters/fishing/clothes/body/floral_fish.tilesource"))
go.property("overall_rod", resource.tile_source("/assets/characters/fishing/clothes/body/overall_fish.tilesource"))
go.property("sailor_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sailor_fish.tilesource"))
go.property("sailor_bow_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sailor_bow_fish.tilesource"))
go.property("sporty_rod", resource.tile_source("/assets/characters/fishing/clothes/body/sporty_fish.tilesource"))
go.property("suit_rod", resource.tile_source("/assets/characters/fishing/clothes/body/suit_fish.tilesource"))

go.property("default_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/basic_hoe.tilesource"))
go.property("floral_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/floral_hoe.tilesource"))
go.property("overall_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/overall_hoe.tilesource"))
go.property("sailor_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sailor_hoe.tilesource"))
go.property("sailor_bow_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sailor_bow_hoe.tilesource"))
go.property("sporty_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/sporty_hoe.tilesource"))
go.property("suit_hoe", resource.tile_source("/assets/characters/hoe/clothes/body/suit_hoe.tilesource"))

go.property("default_watering", resource.tile_source("/assets/characters/watering/clothes/body/basic_watering.tilesource"))
go.property("floral_watering", resource.tile_source("/assets/characters/watering/clothes/body/floral_watering.tilesource"))
go.property("overall_watering", resource.tile_source("/assets/characters/watering/clothes/body/overall_watering.tilesource"))
go.property("sailor_watering", resource.tile_source("/assets/characters/watering/clothes/body/sailor_watering.tilesource"))
go.property("sailor_bow_watering", resource.tile_source("/assets/characters/watering/clothes/body/sailor_bow_watering.tilesource"))
go.property("sporty_watering", resource.tile_source("/assets/characters/watering/clothes/body/sporty_watering.tilesource"))
go.property("suit_watering", resource.tile_source("/assets/characters/watering/clothes/body/suit_watering.tilesource"))

local layer = character_layer.create({
	sprite_url = "#shirt",
	style_kind = "shirt",
})

function init(self)
	layer.init(self)
end

function on_message(self, message_id, message, sender)
	layer.on_message(self, message_id, message)
end
