local character_layer = require("modules.character.character_layer")

go.property("default", resource.tile_source("/assets/characters/walk/eyes/eyes.tilesource"))
go.property("carry", resource.tile_source("/assets/characters/walk/eyes/eyes.tilesource"))
go.property("pickaxe", resource.tile_source("/assets/characters/pickaxe/eyes/eyes_pickaxe.tilesource"))
go.property("sword", resource.tile_source("/assets/characters/sword/eyes/eyes_sword.tilesource"))
go.property("axe", resource.tile_source("/assets/characters/axe/eyes/eyes_axe.tilesource"))
go.property("rod", resource.tile_source("/assets/characters/fishing/eyes/eyes_rod.tilesource"))
go.property("hoe", resource.tile_source("/assets/characters/hoe/eyes/eyes_hoe.tilesource"))
go.property("watering", resource.tile_source("/assets/characters/watering/eyes/eyes_watering.tilesource"))

local layer = character_layer.create({
	sprite_url = "#eyes",
})

function init(self)
	layer.init(self)
end

function on_message(self, message_id, message, sender)
	layer.on_message(self, message_id, message)
end
