local character_layer = require("modules.character.character_layer")

go.property("default", resource.tile_source("/assets/characters/walk/clothes/shoes/shoes.tilesource"))
go.property("carry", resource.tile_source("/assets/characters/carrying/clothes/shoes/shoes_carry.tilesource"))
go.property("pickaxe", resource.tile_source("/assets/characters/pickaxe/clothes/shoes/shoes_pickaxe.tilesource"))
go.property("sword", resource.tile_source("/assets/characters/sword/clothes/shoes/shoes_sword.tilesource"))
go.property("axe", resource.tile_source("/assets/characters/axe/clothes/shoes/shoes_axe.tilesource"))
go.property("rod", resource.tile_source("/assets/characters/fishing/clothes/shoes/shoes_rod.tilesource"))
go.property("hoe", resource.tile_source("/assets/characters/hoe/clothes/shoes/shoes_hoe.tilesource"))
go.property("watering", resource.tile_source("/assets/characters/watering/clothes/shoes/shoes_watering.tilesource"))

local layer = character_layer.create({
	sprite_url = "#shoes",
})

function init(self)
	layer.init(self)
end

function on_message(self, message_id, message, sender)
	layer.on_message(self, message_id, message)
end
