local character_info = require('modules.character.character_information')
local character_looks = require('modules.character.character_looks')
local character_animation_module = require('modules.character.animation.character_animation')
local character_animation = character_animation_module.new()

local default_pos

go.property("default", resource.tile_source("/assets/characters/walk/hair/buzzcut.tilesource"))
go.property("braids", resource.tile_source("/assets/characters/walk/hair/braids.tilesource"))
go.property("curly", resource.tile_source("/assets/characters/walk/hair/curly.tilesource"))
go.property("emo", resource.tile_source("/assets/characters/walk/hair/emo.tilesource"))
go.property("extralong", resource.tile_source("/assets/characters/walk/hair/extralong.tilesource"))
go.property("frenchcurl", resource.tile_source("/assets/characters/walk/hair/frenchcurl.tilesource"))
go.property("gentleman", resource.tile_source("/assets/characters/walk/hair/gentleman.tilesource"))
go.property("midiwave", resource.tile_source("/assets/characters/walk/hair/midiwave.tilesource"))
go.property("spacebuns", resource.tile_source("/assets/characters/walk/hair/spacebuns.tilesource"))
go.property("wavy", resource.tile_source("/assets/characters/walk/hair/wavy.tilesource"))

go.property("default_carry", resource.tile_source("/assets/characters/carrying/hair/buzzcut_carry.tilesource"))
go.property("braids_carry", resource.tile_source("/assets/characters/carrying/hair/braids_carry.tilesource"))
go.property("curly_carry", resource.tile_source("/assets/characters/carrying/hair/curly_carry.tilesource"))
go.property("emo_carry", resource.tile_source("/assets/characters/carrying/hair/emo_carry.tilesource"))
go.property("extralong_carry", resource.tile_source("/assets/characters/carrying/hair/extralong_carry.tilesource"))
go.property("frenchcurl_carry", resource.tile_source("/assets/characters/carrying/hair/frenchcurl_carry.tilesource"))
go.property("gentleman_carry", resource.tile_source("/assets/characters/carrying/hair/gentleman_carry.tilesource"))
go.property("midiwave_carry", resource.tile_source("/assets/characters/carrying/hair/midiwave_carry.tilesource"))
go.property("spacebuns_carry", resource.tile_source("/assets/characters/carrying/hair/spacebuns_carry.tilesource"))
go.property("wavy_carry", resource.tile_source("/assets/characters/carrying/hair/wavy_carry.tilesource"))

go.property("default_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/buzzcut_pickaxe.tilesource"))
go.property("braids_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/braids_pickaxe.tilesource"))
go.property("curly_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/curly_pickaxe.tilesource"))
go.property("emo_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/emo_pickaxe.tilesource"))
go.property("extralong_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/extralong_pickaxe.tilesource"))
go.property("frenchcurl_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/frenchcurl_pickaxe.tilesource"))
go.property("gentleman_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/gentleman_pickaxe.tilesource"))
go.property("midiwave_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/midiwave_pickaxe.tilesource"))
go.property("spacebuns_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/spacebuns_pickaxe.tilesource"))
go.property("wavy_pickaxe", resource.tile_source("/assets/characters/pickaxe/hair/wavy_pickaxe.tilesource"))

go.property("default_sword", resource.tile_source("/assets/characters/sword/hair/buzzcut_sword.tilesource"))
go.property("braids_sword", resource.tile_source("/assets/characters/sword/hair/braids_sword.tilesource"))
go.property("curly_sword", resource.tile_source("/assets/characters/sword/hair/curly_sword.tilesource"))
go.property("emo_sword", resource.tile_source("/assets/characters/sword/hair/emo_sword.tilesource"))
go.property("extralong_sword", resource.tile_source("/assets/characters/sword/hair/extralong_sword.tilesource"))
go.property("frenchcurl_sword", resource.tile_source("/assets/characters/sword/hair/frenchcurl_sword.tilesource"))
go.property("gentleman_sword", resource.tile_source("/assets/characters/sword/hair/gentleman_sword.tilesource"))
go.property("midiwave_sword", resource.tile_source("/assets/characters/sword/hair/midiwave_sword.tilesource"))
go.property("spacebuns_sword", resource.tile_source("/assets/characters/sword/hair/spacebuns_sword.tilesource"))
go.property("wavy_sword", resource.tile_source("/assets/characters/sword/hair/wavy_sword.tilesource"))

go.property("default_axe", resource.tile_source("/assets/characters/axe/hair/buzzcut_axe.tilesource"))
go.property("braids_axe", resource.tile_source("/assets/characters/axe/hair/braids_axe.tilesource"))
go.property("curly_axe", resource.tile_source("/assets/characters/axe/hair/curly_axe.tilesource"))
go.property("emo_axe", resource.tile_source("/assets/characters/axe/hair/emo_axe.tilesource"))
go.property("extralong_axe", resource.tile_source("/assets/characters/axe/hair/extralong_axe.tilesource"))
go.property("frenchcurl_axe", resource.tile_source("/assets/characters/axe/hair/frenchcurl_axe.tilesource"))
go.property("gentleman_axe", resource.tile_source("/assets/characters/axe/hair/gentleman_axe.tilesource"))
go.property("midiwave_axe", resource.tile_source("/assets/characters/axe/hair/midiwave_axe.tilesource"))
go.property("spacebuns_axe", resource.tile_source("/assets/characters/axe/hair/spacebuns_axe.tilesource"))
go.property("wavy_axe", resource.tile_source("/assets/characters/axe/hair/wavy_axe.tilesource"))

go.property("default_rod", resource.tile_source("/assets/characters/fishing/hair/buzzcut_rod.tilesource"))
go.property("braids_rod", resource.tile_source("/assets/characters/fishing/hair/braids_rod.tilesource"))
go.property("curly_rod", resource.tile_source("/assets/characters/fishing/hair/curly_rod.tilesource"))
go.property("emo_rod", resource.tile_source("/assets/characters/fishing/hair/emo_rod.tilesource"))
go.property("extralong_rod", resource.tile_source("/assets/characters/fishing/hair/extralong_rod.tilesource"))
go.property("frenchcurl_rod", resource.tile_source("/assets/characters/fishing/hair/frenchcurl_rod.tilesource"))
go.property("gentleman_rod", resource.tile_source("/assets/characters/fishing/hair/gentleman_rod.tilesource"))
go.property("midiwave_rod", resource.tile_source("/assets/characters/fishing/hair/midiwave_rod.tilesource"))
go.property("spacebuns_rod", resource.tile_source("/assets/characters/fishing/hair/spacebuns_rod.tilesource"))
go.property("wavy_rod", resource.tile_source("/assets/characters/fishing/hair/wavy_rod.tilesource"))

go.property("default_hoe", resource.tile_source("/assets/characters/hoe/hair/buzzcut_hoe.tilesource"))
go.property("braids_hoe", resource.tile_source("/assets/characters/hoe/hair/braids_hoe.tilesource"))
go.property("curly_hoe", resource.tile_source("/assets/characters/hoe/hair/curly_hoe.tilesource"))
go.property("emo_hoe", resource.tile_source("/assets/characters/hoe/hair/emo_hoe.tilesource"))
go.property("extralong_hoe", resource.tile_source("/assets/characters/hoe/hair/extralong_hoe.tilesource"))
go.property("frenchcurl_hoe", resource.tile_source("/assets/characters/hoe/hair/frenchcurl_hoe.tilesource"))
go.property("gentleman_hoe", resource.tile_source("/assets/characters/hoe/hair/gentleman_hoe.tilesource"))
go.property("midiwave_hoe", resource.tile_source("/assets/characters/hoe/hair/midiwave_hoe.tilesource"))
go.property("spacebuns_hoe", resource.tile_source("/assets/characters/hoe/hair/spacebuns_hoe.tilesource"))
go.property("wavy_hoe", resource.tile_source("/assets/characters/hoe/hair/wavy_hoe.tilesource"))

go.property("default_watering", resource.tile_source("/assets/characters/watering/hair/buzzcut_watering.tilesource"))
go.property("braids_watering", resource.tile_source("/assets/characters/watering/hair/braids_watering.tilesource"))
go.property("curly_watering", resource.tile_source("/assets/characters/watering/hair/curly_watering.tilesource"))
go.property("emo_watering", resource.tile_source("/assets/characters/watering/hair/emo_watering.tilesource"))
go.property("extralong_watering", resource.tile_source("/assets/characters/watering/hair/extralong_watering.tilesource"))
go.property("frenchcurl_watering", resource.tile_source("/assets/characters/watering/hair/frenchcurl_watering.tilesource"))
go.property("gentleman_watering", resource.tile_source("/assets/characters/watering/hair/gentleman_watering.tilesource"))
go.property("midiwave_watering", resource.tile_source("/assets/characters/watering/hair/midiwave_watering.tilesource"))
go.property("spacebuns_watering", resource.tile_source("/assets/characters/watering/hair/spacebuns_watering.tilesource"))
go.property("wavy_watering", resource.tile_source("/assets/characters/watering/hair/wavy_watering.tilesource"))

local function get_hair_style(self)
    if character_info.is_carrying then
        local styles = {
            self.braids_carry,
            self.curly_carry,
            self.emo_carry,
            self.extralong_carry,
            self.frenchcurl_carry,
            self.gentleman_carry,
            self.midiwave_carry,
            self.spacebuns_carry,
            self.wavy_carry
        }
        return styles[character_looks.style[1]] or self.default_carry
    else
        local styles = {
            self.braids,
            self.curly,
            self.emo,
            self.extralong,
            self.frenchcurl,
            self.gentleman,
            self.midiwave,
            self.spacebuns,
            self.wavy
        }
        return styles[character_looks.style[1]] or self.default
    end
end

local function get_tool_hair_style(self, action)
    print('action',action)
    if action == 'pickaxe' then
        local styles = {
            self.braids_pickaxe,
            self.curly_pickaxe,
            self.emo_pickaxe,
            self.extralong_pickaxe,
            self.frenchcurl_pickaxe,
            self.gentleman_pickaxe,
            self.midiwave_pickaxe,
            self.spacebuns_pickaxe,
            self.wavy_pickaxe
        }
        return styles[character_looks.style[1]] or self.default_pickaxe
    elseif action == 'axe' then
        local styles = {
            self.braids_axe,
            self.curly_axe,
            self.emo_axe,
            self.extralong_axe,
            self.frenchcurl_axe,
            self.gentleman_axe,
            self.midiwave_axe,
            self.spacebuns_axe,
            self.wavy_axe
        }
        return styles[character_looks.style[1]] or self.default_axe
    elseif action == 'sword' then
        local styles = {
            self.braids_sword,
            self.curly_sword,
            self.emo_sword,
            self.extralong_sword,
            self.frenchcurl_sword,
            self.gentleman_sword,
            self.midiwave_sword,
            self.spacebuns_sword,
            self.wavy_sword
        }
        return styles[character_looks.style[1]] or self.default_sword
    elseif action == 'rod' then
        local styles = {
            self.braids_rod,
            self.curly_rod,
            self.emo_rod,
            self.extralong_rod,
            self.frenchcurl_rod,
            self.gentleman_rod,
            self.midiwave_rod,
            self.spacebuns_rod,
            self.wavy_rod
        }
        return styles[character_looks.style[1]] or self.default_rod
    elseif action == 'hoe' then
        local styles = {
            self.braids_hoe,
            self.curly_hoe,
            self.emo_hoe,
            self.extralong_hoe,
            self.frenchcurl_hoe,
            self.gentleman_hoe,
            self.midiwave_hoe,
            self.spacebuns_hoe,
            self.wavy_hoe
        }
        return styles[character_looks.style[1]] or self.default_hoe
    elseif action == 'watering' then
        local styles = {
            self.braids_watering,
            self.curly_watering,
            self.emo_watering,
            self.extralong_watering,
            self.frenchcurl_watering,
            self.gentleman_watering,
            self.midiwave_watering,
            self.spacebuns_watering,
            self.wavy_watering
        }
        return styles[character_looks.style[1]] or self.default_watering
    end
    return self.default_pickaxe
end


function init(self)
	print(msg.url())
	msg.post(".", "acquire_input_focus")
    default_pos = go.get_position()
	character_animation.reset_animation("#hair", get_hair_style(self), true)
end

function on_input(self, action_id, action)
	if action_id == hash("pickaxe") and action.released then
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'pickaxe'))
	end

	if action_id == hash("axe") and action.released then
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'axe'))
	end

	if action_id == hash("sword") and action.released then
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'sword'))
	end

	if action_id == hash("rod") and action.released then
		go.set_position(vmath.vector3(0, -4, 0))
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'rod'))
	end

	if action_id == hash("hoe") and action.released then
		if character_info.direction == 'down' then
			go.set_position(vmath.vector3(0, -7, 0))
		end
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'hoe'))
	end

	if action_id == hash("watering") and action.released then
		go.set_position(vmath.vector3(0, -5, 0))
		character_animation.start_animation("#hair", get_tool_hair_style(self, 'watering'))
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash('reset_animation') then
		character_animation.reset_animation("#hair", get_hair_style(self), true)
	elseif message_id == hash("animate") then
		character_animation.play_animation("#hair", message.direction)
	end

	character_animation.on_message(message_id, "#hair", get_hair_style(self), default_pos)
end